on:
  push:
    branches:
      - main

name: release-please

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.releases_created }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
        if: ${{ steps.release.outputs.releases_created }}

      - name: Publish to npm
        run: |
          npm ci
          npm run build
          npm run test
          npm config set //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}
          npm publish --access public
        if: ${{ steps.release.outputs.releases_created }}
